---
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    mem_limit: 512m
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kyiv
      - WEBUI_PORT=8080
    volumes:
      - /home/vintobolt/Projects/containers/qbittorrent/config:/config
      #- qbittorent_data:/config
      - /mnt/:/downloads
    networks:
      - traefik_proxy
    ports:
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbittorrent.entrypoints=http"
      - "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.lolcat.home`)"
      - "traefik.http.middlewares.qbittorrent-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.qbittorrent.middlewares=qbittorrent-https-redirect"
      - "traefik.http.routers.qbittorrent-secure.entrypoints=https"
      - "traefik.http.routers.qbittorrent-secure.rule=Host(`qbittorrent.lolcat.home`)"
      - "traefik.http.routers.qbittorrent-secure.tls=true"
      - "traefik.http.routers.qbittorrent-secure.service=qbittorrent"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik_proxy"

#volumes:
#   qbittorent_data:

networks:
  traefik_proxy:
    external: true