---
services:
  pgadmin4:
    image: dpage/pgadmin4
    volumes:
      - pgadmin_data:/var/www/html
    restart: unless-stopped
    networks: 
      - traefik_proxy
    environment:
      - PGADMIN_DEFAULT_EMAIL=vintobolt@lolcathost.pp.ua
      - PGADMIN_DEFAULT_PASSWORD=123456
      - PGADMIN_DEFAULT_USER=vintobolt
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.entrypoints=http"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.lolcat.home`)"
      - "traefik.http.middlewares.pgadmin-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.pgadmin.middlewares=pgadmin-https-redirect"
      - "traefik.http.routers.pgadmin-secure.entrypoints=https"
      - "traefik.http.routers.pgadmin-secure.rule=Host(`pgadmin.lolcat.home`)"
      - "traefik.http.routers.pgadmin-secure.tls=true"
      - "traefik.http.routers.pgadmin-secure.service=pgadmin"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_proxy"
      

networks:
  traefik_proxy:
    external: true

volumes:
  pgadmin_data: