services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik_proxy
    restart: unless-stopped
    mem_limit: 2048m
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.entrypoints=http"
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.lolcat.home`)"
      - "traefik.http.middlewares.jenkins-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.jenkins.middlewares=jenkins-https-redirect"
      - "traefik.http.routers.jenkins-secure.entrypoints=https"
      - "traefik.http.routers.jenkins-secure.rule=Host(`jenkins.lolcat.home`)"
      - "traefik.http.routers.jenkins-secure.tls=true"
      - "traefik.http.routers.jenkins-secure.service=jenkins"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik_proxy"
  
volumes:
  jenkins_home:

networks:
  traefik_proxy:
    external: true