services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - "traefik.enable=true"
      # http
      - "traefik.http.routers.portainer-http.entrypoints=http"
      - "traefik.http.routers.portainer-http.rule=Host(`portainer.lolcat.home`)"
      # https
      - "traefik.http.routers.portainer.entrypoints=https"
      - "traefik.http.routers.portainer.rule=Host(`portainer.lolcat.home`)"
      - "traefik.http.routers.portainer.tls=true"
      # middlewares
      - "traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.portainer.middlewares=portainer-https-redirect"
      # service
      - "traefik.http.services.portainer-service.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.service=portainer-service"
      # network
      - "traefik.docker.network=traefik_proxy"
    restart: unless-stopped
    networks:
      - traefik_proxy
  
networks:
  traefik_proxy:
    external: true

volumes:
  portainer_data: